version: "3"
services:
  dispatch-engine:
    container_name: "dispatch-engine"
    environment:
      - MODULE_NAME=app.main                            # or custom_app:custom_main
      - VARIABLE_NAME=app                               # or some custom_var
      #- GUNICORN_CONF="/app/custom_gunicorn_conf.py"
      - WORKERS_PER_CORE=1                              # by default 1
      - WEB_CONCURRENCY=2                               # by default 2
      - HOST=0.0.0.0                                    # by default 0.0.0.0
      - PORT=5000                                       # by default 80
      - LOG_LEVEL=info                                  # by default info
      #- WORKER_CLASS="uvicorn.workers.UvicornWorker"   # by default this. don't touch
      - TIMEOUT=120                                     # by default 120 sec

    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  redis:
    container_name: redis-cont
    image: "redis:alpine"
    environment:
      - REDIS_PASSWORD=debian
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      # save redisearch data to your current working directory
      - ./redis-data:/data
    command:
      # Save if 100 keys are added in every 10 seconds
      - "--save 10 100"
      # Set password
      - "--requirepass debian"

volumes:
  redis-data:
